---
functional:
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - Просмотр каталога товаров
  - Система фильтрации товаров по одному или нескольким критериям
  - Сброс выбранных фильтров
  - Управление корзиной - добавление товара, просмотр информации, удаление товара
  - Оформление товара с переходом на страницу оплаты
  - Переход на страницу товара из каталога
  - Возможность продолжить покупки из корзины
  - Просмотр информации о товаре - название, рейтинг, цена со скидкой и без нее
  - Сохранение состояния корзины в сессии браузера
non-functional:
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  - Адаптивная верстка для мобильных устройств
  - Реализация SPA-приложения
implicit:
  - У пользователя должен быть личный кабинет с логином и паролем
  - Невозможность вывода отрицательной стоимости товара
  - Доступность сайта в режиме работы 24/7 без перерывов
  - Клиенту должно поступать уведомление о подтверждениии заказа товара
  - Пользователь должен иметь возможность удалять ненужные товары из корзины
